#!/usr/bin/env bash
################################################################################
# *** auto-generated by (github.com/FrankyMartz/dotfiles) ***
# Env Bash Config
#
# Author:   Franky Martinez <frankymartz@gmail.com>
################################################################################

export LANG=en_US.UTF-8;

# ------------------------------------------------------------------------------
# PATH: Default
# ------------------------------------------------------------------------------

export PATH="/usr/sbin:/sbin:${PATH}";
export XDG_CONFIG_HOME="${HOME}/.config";
export XDG_DATA_HOME="${HOME}/.config/nvim";

export PATH="${PATH}:${HOME}/.gem/ruby/2.6.0/bin"

# ------------------------------------------------------------------------------
# Homebrew
# ------------------------------------------------------------------------------

if ! command -v brew &>/dev/null; then
  for _brew_path in /opt/homebrew/bin/brew /usr/local/bin/brew /home/linuxbrew/.linuxbrew/bin/brew; do
    if [[ -x "${_brew_path}" ]]; then
      eval "$("${_brew_path}" shellenv)"
      break
    fi
  done
  unset _brew_path
fi

# Ensure Homebrew bin/sbin take priority over system paths.
# brew shellenv calls path_helper which reorders PATH, putting /usr/bin first.
if [[ -n "${HOMEBREW_PREFIX}" ]]; then
  export PATH="${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin:${PATH}"
fi

# ------------------------------------------------------------------------------
# Foundation
# ------------------------------------------------------------------------------

if [[ -d "${HOME}/.iterm2" ]]; then
  export PATH="${PATH}:${HOME}/.iterm2";
fi

# GNU --------------------------------------------------------------------------

if [[ -n "${HOMEBREW_PREFIX}" ]]; then
  _gnubin="${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnubin"
  _gnuman="${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnuman"
  [[ -d "${_gnubin}" ]] && export PATH="${_gnubin}:${PATH}"
  [[ -d "${_gnuman}" ]] && export MANPATH="${_gnuman}:${MANPATH}"
  unset _gnubin _gnuman
fi

# BAT --------------------------------------------------------------------------

if [[ $ITERM_PROFILE == "Light" ]]; then
  export BAT_THEME="Solarized (light)";
else
  export BAT_THEME='OneHalfDark';
fi

# NEOVIM -----------------------------------------------------------------------

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim';
else
  export EDITOR='nvim';
fi

# IRC --------------------------------------------------------------------------

export IRCNICK="frankymartz";
export IRCNAME="No Konami Code.";
export IRCSERVER="http://chat.freenode.net";

#===============================================================================
# LANGUAGES
#===============================================================================

# PYTHON -----------------------------------------------------------------------

if [[ -x "$(command -v pyenv)" ]]; then
  PYENV_ROOT="${HOMEBREW_PREFIX}/opt/pyenv";
  export PYENV_ROOT
  # export PYENV_ROOT="${HOME}/.pyenv";
  export PATH="${PYENV_ROOT}/bin:${PATH}"
  export PYTHON_CONFIGURE_OPTS="--enable-shared";
  eval "$(pyenv init --path)";
  if [[ -d "${HOMEBREW_PREFIX}/opt/pyenv-virtualenv" ]]; then
    eval "$(pyenv virtualenv-init -)"
  fi
  # PIPX
  export PATH="$PATH:${HOME}/.local/bin"
fi

# GO-LANG ----------------------------------------------------------------------

if [[ -x "$(command -v go)" ]]; then
  GOROOT="${HOMEBREW_PREFIX}/opt/go/libexec";
  export GOROOT;
  export GOPATH="${HOME}/go";
  export PATH="${PATH}:${GOROOT}/bin:${GOPATH}/bin";
fi

# RUBY -------------------------------------------------------------------------

if [[ -x "$(command -v rbenv)" ]]; then
  if [[ "$0" == *zsh ]]; then
    eval "$(rbenv init - --no-rehash zsh)"
  else
    eval "$(rbenv init -)";
  fi
fi

# NodeJS -----------------------------------------------------------------------

if [[ -x "$(command -v volta)" ]]; then
  export VOLTA_HOME="${HOME}/.volta";
  export PATH="${VOLTA_HOME}/bin:${PATH}"
  unset _VOLTA_TOOL_RECURSION
fi

# Rust -------------------------------------------------------------------------

if [[ -x "$(command -v rustc)" ]];then
  export PATH="${HOME}/.cargo/bin:${PATH}";
fi

# JAVA -------------------------------------------------------------------------


if [[ -d "/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home" ]]; then
  export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home";
fi

# PostgreSQL -------------------------------------------------------------------

if [[ -d "${HOMEBREW_PREFIX}/opt/libpq/bin" ]]; then
  export PATH="${PATH}:${HOMEBREW_PREFIX}/opt/libpq/bin"
fi

# Android ----------------------------------------------------------------------

if [[ -d "$HOME/Library/Android/sdk" ]]; then
  export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
  export ANDROID_HOME="$HOME/Library/Android/sdk"
  export PATH="$PATH:$ANDROID_SDK_ROOT/emulator"
  export PATH="$PATH:$ANDROID_SDK_ROOT/platform-tools"
  export PATH="$PATH:$ANDROID_HOME/platform-tools"
  export PATH="$PATH:$ANDROID_HOME/cmdline-tools/10.0/bin"
fi

#===============================================================================
# Tools
#===============================================================================

# Jetbrains --------------------------------------------------------------------

if [[ -d "$HOME/Library/Application Support/JetBrains/Toolbox/scripts" ]]; then
  export PATH="$PATH:${HOME}/Library/Application Support/JetBrains/Toolbox/scripts"
fi


# uv
export PATH="/Users/frankymartz/.config/nvim/../bin:$PATH"
