#!/usr/bin/env bash
################################################################################
# *** auto-generated by (github.com/FrankyMartz/dotfiles) ***
# Env Bash Config
#
# Author:   Franky Martinez <frankymartz@gmail.com>
################################################################################

export LANG=en_US.UTF-8;

# ------------------------------------------------------------------------------
# PATH: Default
# ------------------------------------------------------------------------------

export PATH="/usr/sbin:/sbin:${PATH}";
export XDG_CONFIG_HOME="${HOME}/.config";
export XDG_DATA_HOME="${HOME}/.config/nvim";

export PATH="${PATH}:${HOME}/.gem/ruby/2.6.0/bin"

# ------------------------------------------------------------------------------
# Homebrew
# ------------------------------------------------------------------------------

if [[ -x "/opt/homebrew/bin/brew" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# ------------------------------------------------------------------------------
# Foundation
# ------------------------------------------------------------------------------

if [[ -d "${HOME}/.iterm2" ]]; then
  export PATH="${PATH}:${HOME}/.iterm2";
fi

# GNU --------------------------------------------------------------------------

if [[ -x "$(command -v brew)" ]]; then
  export MANPATH="${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnubin:$MANPATH"
fi

# BAT --------------------------------------------------------------------------

if [[ $ITERM_PROFILE == "Light" ]]; then
  export BAT_THEME="Solarized (light)";
else
  export BAT_THEME='OneHalfDark';
fi

# NEOVIM -----------------------------------------------------------------------

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim';
else
  export EDITOR='nvim';
fi

# IRC --------------------------------------------------------------------------

export IRCNICK="frankymartz";
export IRCNAME="No Konami Code.";
export IRCSERVER="http://chat.freenode.net";

#===============================================================================
# LANGUAGES
#===============================================================================

# PYTHON -----------------------------------------------------------------------

if [[ -x "$(command -v pyenv)" ]]; then
  PYENV_ROOT="$(brew --prefix pyenv)";
  export PYENV_ROOT
  # export PYENV_ROOT="${HOME}/.pyenv";
  export PATH="${PYENV_ROOT}/bin:${PATH}"
  export PYTHON_CONFIGURE_OPTS="--enable-shared";
  eval "$(pyenv init --path)";
fi

# GO-LANG ----------------------------------------------------------------------

if [[ -x "$(command -v go)" ]]; then
  GOROOT="$(brew --prefix go)/libexec";
  export GOROOT;
  export GOPATH="${HOME}/go";
  export PATH="${PATH}:${GOROOT}/bin:${GOPATH}/bin";
fi

# RUBY -------------------------------------------------------------------------

if [[ -x "$(command -v rbenv)" ]]; then
  eval "$(rbenv init -)";
fi

# NodeJS -----------------------------------------------------------------------

if [[ -x "$(brew --prefix volta)" ]]; then
  export VOLTA_HOME="${HOME}/.volta";
  export PATH="${VOLTA_HOME}/bin:${PATH}"
  unset _VOLTA_TOOL_RECURSION
fi

# Rust -------------------------------------------------------------------------

if [[ -x "$(command -v rust)" ]];then
  export PATH="${HOME}/.cargo/bin:${PATH}";
fi

# JAVA -------------------------------------------------------------------------


if [[ -d "/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home" ]]; then
  export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home";
fi

# PostgreSQL -------------------------------------------------------------------

if [[ -x "$(brew --prefix libpq)/bin" ]]; then
  export PATH="${PATH}:/opt/homebrew/opt/libpq/bin"
fi

# Android ----------------------------------------------------------------------

if [[ -d "$HOME/Library/Android/sdk" ]]; then
  export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
  export ANDROID_HOME="$HOME/Library/Android/sdk"
  export PATH="$PATH:$ANDROID_SDK_ROOT/emulator"
  export PATH="$PATH:$ANDROID_SDK_ROOT/platform-tools"
  export PATH="$PATH:$ANDROID_HOME/platform-tools"
  export PATH="$PATH:$ANDROID_HOME/cmdline-tools/10.0/bin"
fi
