#!/usr/bin/env bash
################################################################################
# *** auto-generated by (github.com/FrankyMartz/dotfiles) ***
# Shell Alias
#
# Author:   Franky Martinez <frankymartz@gmail.com>
################################################################################

#===============================================================================
# ALIASES
#===============================================================================

# alias less='less --RAW-CONTROL-CHARS';
export LESSOPEN="| $(which highlight) %s --out-format xterm256 --line-numbers --quiet --force --style solarized-light"
export LESS=" -R"
alias less='less -m -N -g -i -J --line-numbers --underline-special'
alias more='less'

# Use "highlight" in place of "cat"
alias cat="highlight $1 --out-format xterm256 --line-numbers --quiet --force --style solarized-light"

alias la='ls -lAFh --color --group-directories-first'; # color-mode
alias irc='screen -t 1 irssi';
alias chrome-cors='open -a Google\ Chrome --args --disable-web-security --user-data-dir';
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome';
alias chrome-canary='/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary';

alias pe='path-extractor';
alias PP='git st | pe | fzf -m | xargs git add && clear && printf "\e[3J" && git st';
alias pass-keygen="openssl rand -base64";

#===============================================================================
# Bind
#===============================================================================
# bind '"CC": "| pe | fzf | pbcopy && clear &&  pbpaste || xargs echo"'
