#!/usr/bin/env zsh
################################################################################
# *** auto-generated by (github.com/FrankyMartz/dotfiles) ***
# .zshrc.zsh (FrankyMartz Flavored ZSH)
#
# Author:   Franky Martinez <frankymartz@gmail.com>
################################################################################

bindkey -v

DOTFILES="${HOME}/.dotfiles"

#===============================================================================
# COMMON
#===============================================================================

export LANG=en_US.UTF-8

[[ -x "${DOTFILES}/shell/alias.sh" ]] && source "${DOTFILES}/shell/alias.sh";

#===============================================================================
# Foundation
#===============================================================================

# Lines configured by zsh-newuser-install
HISTFILE="${DOTFILES}/bin/.zsh_history"
HISTSIZE=5000
SAVEHIST=5000
# 10ms for key sequences
KEYTIMEOUT=1
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep

# DIRENV -----------------------------------------------------------------------

if [[ -x "$(command -v direnv)" ]]; then
  eval "$(direnv hook zsh)"
fi

# ZSH-Completions --------------------------------------------------------------

if [[ -x "$(command -v brew)" ]]; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
  [[ -x "$(brew --prefix)/share/zsh-completions" ]] && FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
  [[ -x "~/.rbenv/completions" ]] && FPATH=~/.rbenv/completions:"$FPATH"
  autoload -Uz compinit
  compinit
fi

#===============================================================================
# PLUGINS
#===============================================================================

# iTerm Integration ------------------------------------------------------------
# shellcheck source=/dev/null
[[ -x "${HOME}/.iterm2_shell_integration.zsh" ]] && source "${HOME}/.iterm2_shell_integration.zsh";

# HOTFIX: https://github.com/zsh-users/antigen/issues/593
# autoload -U is-at-least
# source "${HOME}/.dotfiles/zsh/zsh_plugins.sh"

export BOOKMARKS_FILE="${DOTFILES}/bin/zsh_cd_bookmarks";

# Package: AutoSuggestion ------------------------------------------------------

ZSH_AUTOSUGGEST_USE_ASYNC=true;

# StarShip-Prompt -------------------------------------------------------------

if [[ "$(command -v starship)" ]]; then
  eval "$(starship init zsh)"
  export STARSHIP_CONFIG="${DOTFILES}/shell/starship.toml"
fi

# Google Cloud -----------------------------------------------------------------

if [[ -x "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc" ]]; then
  GoogleCloudSdkPath="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
  source $GoogleCloudSdkPath
fi

if [[ -x "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" ]]; then
  GoogleCloudCompletionPath="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
  source $GoogleCloudCompletionPath
fi

# Git-Town ---------------------------------------------------------------------

[[ -x "$(command -v git-town)" ]] && source <(git-town completions zsh)

