#!/usr/bin/env zsh
################################################################################
# *** auto-generated by (github.com/FrankyMartz/dotfiles) ***
# .zshrc.zsh (FrankyMartz Flavored ZSH)
#
# Author:   Franky Martinez <frankymartz@gmail.com>
################################################################################

bindkey -v

DOTFILES="${HOME}/.dotfiles"

#===============================================================================
# COMMON
#===============================================================================

export LANG=en_US.UTF-8

[[ -x "${DOTFILES}/shell/core.sh" ]] && source "${DOTFILES}/shell/core.sh";
[[ -x "${DOTFILES}/shell/alias.sh" ]] && source "${DOTFILES}/shell/alias.sh";

# shellcheck source=/dev/null
# [[ -f "${HOME}/.fzf.zsh" ]] && source "${HOME}/.fzf.zsh";

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
  autoload -Uz compinit
  compinit
fi

# iTerm Integration ------------------------------------------------------------
# shellcheck source=/dev/null
[[ -x "${HOME}/.iterm2_shell_integration.zsh" ]] && source "${HOME}/.iterm2_shell_integration.zsh";

#===============================================================================
# Foundation
#===============================================================================

# Lines configured by zsh-newuser-install
HISTFILE="${DOTFILES}/bin/.zsh_history"
HISTSIZE=5000
SAVEHIST=5000
# 10ms for key sequences
KEYTIMEOUT=1
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep

#===============================================================================
# PLUGINS
#===============================================================================

# HOTFIX: https://github.com/zsh-users/antigen/issues/593
# autoload -U is-at-least
# source "${HOME}/.dotfiles/zsh/zsh_plugins.sh"

export BOOKMARKS_FILE="${DOTFILES}/bin/zsh_cd_bookmarks";

# Package: AutoSuggestion ------------------------------------------------------

ZSH_AUTOSUGGEST_USE_ASYNC=true;

# StarShip-Prompt -------------------------------------------------------------
#
eval "$(starship init zsh)"
export STARSHIP_CONFIG="${DOTFILES}/shell/zsh/starship.toml"

#===============================================================================
# DOTENV LOAD
#===============================================================================

eval "$(direnv hook zsh)"

#===============================================================================
# Google Cloud 
#===============================================================================

GoogleCloudSdkPath="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
GoogleCloudCompletionPath="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

[[ -x "$GoogleCloudSdkPath" ]] && source "$GoogleCloudSdkPath"
[[ -x "$GoogleCloudCompletionPath" ]] && source "$GoogleCloudCompletionPath"
