#!/usr/bin/env zsh
################################################################################
# *** auto-generated by (github.com/FrankyMartz/dotfiles) ***
# .zshrc.zsh (FrankyMartz Flavored ZSH)
#
# Author:   Franky Martinez <frankymartz@gmail.com>
################################################################################

bindkey -v

DOTFILES="${HOME}/.dotfiles"

#===============================================================================
# COMMON
#===============================================================================

[[ -x "${DOTFILES}/shell/env.sh" ]] && source "${DOTFILES}/shell/env.sh";
[[ -x "${DOTFILES}/shell/alias.sh" ]] && source "${DOTFILES}/shell/alias.sh";

# Re-assert Homebrew/gnubin PATH priority.
# macOS /etc/zprofile runs path_helper AFTER ~/.zshenv, reordering PATH so
# system paths (/usr/bin) come first again. Fix that here in .zshrc.
# if [[ -n "${HOMEBREW_PREFIX}" ]]; then
#   _gnubin="${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnubin"
#   [[ -d "${_gnubin}" ]] && export PATH="${_gnubin}:${PATH}"
#   export PATH="${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin:${PATH}"
#   unset _gnubin
# fi

#===============================================================================
# Foundation
#===============================================================================

# Lines configured by zsh-newuser-install
HISTFILE="${DOTFILES}/bin/.zsh_history"
HISTSIZE=5000
SAVEHIST=5000
# 10ms for key sequences
KEYTIMEOUT=1
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep

# DIRENV -----------------------------------------------------------------------

if [[ -x "$(command -v direnv)" ]]; then
  eval "$(direnv hook zsh)"
fi

#===============================================================================
# PLUGINS
#===============================================================================

# iTerm Integration ------------------------------------------------------------
# shellcheck source=/dev/null
[[ -x "${HOME}/.iterm2_shell_integration.zsh" ]] && source "${HOME}/.iterm2_shell_integration.zsh";

# HOTFIX: https://github.com/zsh-users/antigen/issues/593
# autoload -U is-at-least
# source "${HOME}/.dotfiles/zsh/zsh_plugins.sh"

export BOOKMARKS_FILE="${DOTFILES}/bin/zsh_cd_bookmarks";

# Package: AutoSuggestion ------------------------------------------------------

ZSH_AUTOSUGGEST_USE_ASYNC=true;

# StarShip-Prompt -------------------------------------------------------------

if [[ "$(command -v starship)" ]]; then
  eval "$(starship init zsh)"
  export STARSHIP_CONFIG="${DOTFILES}/shell/starship.toml"
fi

# Google Cloud -----------------------------------------------------------------

if [[ -x "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc" ]]; then
  GoogleCloudSdkPath="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
  source $GoogleCloudSdkPath
fi

if [[ -x "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc" ]]; then
  GoogleCloudCompletionPath="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
  source $GoogleCloudCompletionPath
fi

# Git-Town ---------------------------------------------------------------------

[[ -x "$(command -v git-town)" ]] && source <(git-town completions zsh)

# NGROK ------------------------------------------------------------------------

if [[ -x "$(command -v ngrok)" ]]; then
  eval "$(ngrok completion)"
fi

