#!/usr/bin/env zsh
################################################################################
# *** auto-generated by (github.com/FrankyMartz/dotfiles) ***
# FrankyMartz Flavored ZPLUG
#
# Author:   Franky Martinez <frankymartz@gmail.com>
################################################################################

export ZPLUG_HOME="${HOME}/.zplug";
[[ -f "${ZPLUG_HOME}/init.zsh" ]] && source "${ZPLUG_HOME}/init.zsh";
# zplug clear;

zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Package ======================================================================
# Package: General -------------------------------------------------------------

zplug "mafredri/zsh-async", from:github, as:plugin;
zplug "supercrabtree/k", from:github, as:plugin;
zplug "zsh-users/zsh-completions", from:github, as:plugin;

# Package: AutoSuggestion ------------------------------------------------------

zplug "zsh-users/zsh-autosuggestions", from:github, as:plugin;
ZSH_AUTOSUGGEST_USE_ASYNC=true;

# ------------------------------------------------------------------------------

zplug "zsh-users/zsh-history-substring-search";
# NOTE: Use (FZF) instead
# zplug "b4b4r07/enhancd", from:github, as:plugin, use:init.sh;

# ------------------------------------------------------------------------------

zplug "jocelynmallon/zshmarks", from:github, as:plugin;
export BOOKMARKS_FILE="${DOTFILE_DIR}/bin/zsh_cd_bookmarks";

# Package: OhMyZsh -------------------------------------------------------------

zplug "plugins/common-aliases", from:oh-my-zsh;
zplug "plugins/vim-mode", from:oh-my-zsh;
zplug "plugins/git-extras", from:oh-my-zsh;

# Package: Prompt --------------------------------------------------------------

# zplug "sindresorhus/pure", use:pure.zsh, from:github, as:theme
zplug "denysdovhan/spaceship-prompt", from:github, as:theme, use:spaceship.zsh;

# SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SUFFIX=" "; # 
SPACESHIP_CHAR_SYMBOL=""; #       

# SPACESHIP_VI_MODE_SHOW=true;
SPACESHIP_VI_MODE_PREFIX=" "; # [ 
# SPACESHIP_VI_MODE_SUFFIX=" "; # ] 
SPACESHIP_VI_MODE_INSERT="卑"; #  卑    
SPACESHIP_VI_MODE_NORMAL="喝"; #  喝        
SPACESHIP_VI_MODE_COLOR="cyan";


SPACESHIP_GIT_SYMBOL=" ";
SPACESHIP_GIT_STATUS_UNTRACKED="";
SPACESHIP_GIT_STATUS_ADDED="●"; #  ● ✚
SPACESHIP_GIT_STATUS_MODIFIED="";
SPACESHIP_GIT_STATUS_RENAMED="➡"; #   
SPACESHIP_GIT_STATUS_DELETED="";
SPACESHIP_GIT_STATUS_STASHED="";
SPACESHIP_GIT_STATUS_UNMERGED=" ";
SPACESHIP_GIT_STATUS_AHEAD="⬆";
SPACESHIP_GIT_STATUS_BEHIND="⬇";
SPACESHIP_GIT_STATUS_DIVERGED=" ";


# Syntax Highlighting ----------------------------------------------------------
# MUST be sourced after all custom widgets
zplug "zsh-users/zsh-syntax-highlighting", from:github, as:plugin, defer:2;

# Handle =======================================================================

# Missing Package --------------------------------------------------------------

zplug check || zplug install;

# INIT =========================================================================

zplug load;

# INIT =========================================================================

spaceship_vi_mode_enable
