#!/usr/bin/env zsh
################################################################################
# *** auto-generated by (github.com/FrankyMartz/dotfiles) ***
# FrankyMartz Flavored ZSH
#
# Author:   Franky Martinez <frankymartz@gmail.com>
################################################################################

bindkey -v
# # export KEYTIMEOUT=1
# precmd() { RPROMPT="" }
DOTFILE_DIR="${HOME}/.dotfiles"

#===============================================================================
# COMMON
#===============================================================================

export LANG=en_US.UTF-8

# shellcheck source=/dev/null
[[ -f "${HOME}/.fzf.zsh" ]] && source "${HOME}/.fzf.zsh";
[[ -f "${DOTFILE_DIR}/bashrc.sh" ]] && source "${DOTFILE_DIR}/bashrc.sh";
[[ -f "${DOTFILE_DIR}/alias.sh" ]] && source "${DOTFILE_DIR}/alias.sh";

if type brew &>/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:$FPATH"
  autoload -Uz compinit
  compinit
fi

# iTerm Integration ------------------------------------------------------------
# shellcheck source=/dev/null
[[ -x "${HOME}/.iterm2_shell_integration.zsh" ]] && source "${HOME}/.iterm2_shell_integration.zsh";

#===============================================================================
# Foundation
#===============================================================================

# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=5000
SAVEHIST=5000
# 10ms for key sequences
KEYTIMEOUT=1
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep

#===============================================================================
# PLUGINS
#===============================================================================

# HOTFIX: https://github.com/zsh-users/antigen/issues/593
# autoload -U is-at-least
# source "${HOME}/.dotfiles/zsh/zsh_plugins.sh"

export BOOKMARKS_FILE="${DOTFILE_DIR}/bin/zsh_cd_bookmarks";

# Package: AutoSuggestion ------------------------------------------------------

ZSH_AUTOSUGGEST_USE_ASYNC=true;

# StarShip-Prompt -------------------------------------------------------------

if [ -x "$(command -v starship)" ]; then
	eval "$(starship init zsh)"
	export STARSHIP_CONFIG="${DOTFILE_DIR}/starship.toml"
fi

#===============================================================================
# Alias
#===============================================================================

[[ -f "${DOTFILE_DIR}/alias.sh" ]] && source "${DOTFILE_DIR}/alias.sh";

#===============================================================================
# DOTENV LOAD
#===============================================================================

[[ -x "$(command -v direnv)" ]] && eval "$(direnv hook zsh)"

#===============================================================================
# Google Cloud 
#===============================================================================

# export PATH="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:${PATH}"
# GoogleCloudSdkPath="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
# GoogleCloudCompletionPath="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

# [[ -x "$GoogleCloudSdkPath" ]] && source "$GoogleCloudSdkPath"
# [[ -x "$GoogleCloudCompletionPath" ]] && source "$GoogleCloudCompletionPath"
