#!/usr/bin/env sh
################################################################################
# *** auto-generated by (github.com/FrankyMartz/dotfiles) ***
# FrankyMartz Flavored Bash Shell
#
# Author:   Franky Martinez <frankymartz@gmail.com>
# Version:  0.1.0
################################################################################
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/git/bin

#===============================================================================
# General
export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH
export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH
export MANPATH=$(brew --prefix coreutils)/libexec/gnuman:$MANPATH
export TERM='xterm-256color'
stty -ixon -ixoff

#if [[ -x "$(brew --prefix)/bin/bash" ]]; then
    #export BASH="$(brew --prefix)/bin/bash"
#fi

#===============================================================================
# PROMPT LOOK
#===============================================================================

# Base16-Shell -----------------------------------------------------------------
BASE16_SHELL="$HOME/.dotfiles/bin/base16-shell/base16-eighties.dark.sh"
[[ -s "$BASE16_SHELL" ]] && source "$BASE16_SHELL"

# BASH_POWERLINE ---------------------------------------------------------------
source "$HOME/.dotfiles/bash/bash_powerline.sh"

#===============================================================================
# IRC
#===============================================================================
export IRCNICK='frankymartz'
export IRCNAME='No Konami Code.'
export IRCSERVER=http://chat.freenode.net


#===============================================================================
# ALIASES
#===============================================================================
alias ll='ls -FAlhG --color --group-directories-first' # color-mode
alias irc='screen -t 1 irssi'

alias vi='nvim'
alias vim='nvim'


#===============================================================================
# BASH COMPLETION
#===============================================================================
if [ -f "$(brew --prefix)/etc/bash_completion" ]; then
    . "$(brew --prefix)/etc/bash_completion"
fi


#===============================================================================
# LANGUAGES
#===============================================================================

# Google Cloud SDK -------------------------------------------------------------
# The next line updates PATH for the Google Cloud SDK.
source "${HOME}/google-cloud-sdk/path.bash.inc"
# The next line enables bash completion for gcloud.
source "${HOME}/google-cloud-sdk/completion.bash.inc"

# PYTHON -----------------------------------------------------------------------
export PYTHONPATH=~/.dotfiles/bin/python
# Auto-Complete
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
export PYENV_ROOT=/usr/local/var/pyenv

# GO-LANG ----------------------------------------------------------------------
export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/go:~/go_appengine/gopath
#export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
#export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/go_appengine

# NVM --------------------------------------------------------------------------
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# RBENV ------------------------------------------------------------------------
## Use Homebrew's directories rather than ~/.rbenv add to your profile
export RBENV_ROOT=/usr/local/var/rbenv

## Enable shims and autocompletion add to your profile
if which rbenv > /dev/null; then
	eval "$(rbenv init -)";
fi

if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi

# PHP --------------------------------------------------------------------------
export PATH=$PATH:~/.composer/vendor/bin

# Docker -----------------------------------------------------------------------
export DOCKER_HOST=tcp://192.168.23.2:2375
#export DOCKER_HOST=tcp://localhost:2376
#export DOCKER_CERT_PATH=$HOME/.boot2docker/certs/boot2docker-vm
#export DOCKER_TLS_VERIFY=1


#===============================================================================
# PROJECT
#===============================================================================

# NCMS -------------------------------------------------------------------------
export GABO=~/Projects/gweb-gabo/default

# Trunk Club--------------------------------------------------------------------
export DOCKER_HOST=tcp://192.168.23.2:2375
